name: CI - Hola Mundo

on:
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  hola:
    runs-on: ubuntu-latest
    steps:
      - name: Mensaje
        run: echo "Hola mundo desde un Pull Request 👋✅ hi hi hi!"
